### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by christianreiss** [SmartHomeIntegrationTech/MQTTServices-Daikin#5]
This is perfect. 

Now my Daikin is talking to homeassistant via MQTT and I can skip the entire Smart Grid stuff with even smarter logic.
Is it possible to get the current outside unit mode? I would like to know if it's idle or running. And even better: If the heat pump currently heats the UFH or DHW. 

Thank you again. You are the ONLY solution to the Altherma problem out there (that works). Keep developing; I am sure I am not the only one who only with your help got their Daikin Heat Pump working.

A pitty even. The AC units from daikin work FLAWLESS via their wlan adaptors in HA.

Oh well.

Thank you again,

**Comment by jaakla** [comment]
> How is it integrated to HA ?

@haz-69 I did it via plain MQTT - you configure interesting sensors and setters there. There is no autoconfiguration or detection of integration, as MQTT messages are homie-specific. Sensor config sample:
```yaml
sensor:
  - platform: mqtt
    state_topic: "homie/daikin-heatingunit/spaceheating/1-sensor-outdoortemperature"
    name: "Daikin outside"
    unit_of_measurement: "°C"
```
